trigger:
  branches:
    include:
      - main  # specify the branch to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'  # Use an Ubuntu image for the pipeline

jobs:
  - job: SnykScan
    displayName: 'Snyk Vulnerability Scan'
    steps:
      # Install Node.js manually if UseNode task is not available
      - script: |
          curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
        displayName: 'Install Node.js'

      - script: |
          npm install -g snyk  # Install the Snyk CLI globally
        displayName: 'Install Snyk CLI'

      - script: |
          snyk auth $(SNYK_TOKEN)  # Authenticate with your Snyk API token
          snyk test --all-projects --json > snyk-report.json  # Run the Snyk scan and output to JSON
        displayName: 'Run Snyk Test'
        env:
          SNYK_TOKEN: $(SNYK_TOKEN)  # Ensure you have added your Snyk token as a secret in Azure DevOps

      # Publish the JSON report as an artifact
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: 'snyk-report.json'
          artifactName: 'SnykReport'
          publishLocation: 'Container'

      # Convert the JSON report to PDF using Pandoc
      - script: |
          sudo apt-get install -y pandoc  # Install Pandoc to convert the JSON report to PDF
          pandoc snyk-report.json -o snyk-report.pdf  # Convert the JSON report to PDF
        displayName: 'Convert JSON report to PDF'

      # Publish the PDF report as an artifact
      - task: PublishBuildArtifacts@1
        inputs:
          pathToPublish: 'snyk-report.pdf'
          artifactName: 'SnykPDFReport'
          publishLocation: 'Container'
