trigger:
- main  # Adjust as needed for your branch

pool:
  vmImage: ubuntu-latest  # Use an appropriate agent pool (change if required)

steps:
  # Step 1: Create results directory before running the scan
  - script: |
      mkdir -p $(Build.ArtifactStagingDirectory)/results  # Ensure the results directory exists
    displayName: 'Create results directory'

  # Step 2: Run Snyk Security Scan on Code with Authentication via Service Connection
  - task: SnykSecurityScan@1
    inputs:
      serviceConnectionEndpoint: 'SNYKS'  # Use your correct service connection name
      testType: 'code'  # Scan the source code for vulnerabilities
      failOnIssues: false  # Do NOT fail the build regardless of issues found
      projectName: 'your-project-name'  # Set your project name (auto-filled in the UI)
      organizationName: 'your-org-name'  # Set your Snyk organization name (auto-filled in the UI)
    displayName: 'Run Snyk Code Security Scan'

  # Step 3: Move Snyk Reports to Results Directory
  - script: |
      # Ensure Snyk reports are generated in the results directory
      mv /home/vsts/work/_temp/snyk-*.json $(Build.ArtifactStagingDirectory)/results/ || echo "No JSON files generated"
      mv /home/vsts/work/_temp/snyk-*.html $(Build.ArtifactStagingDirectory)/results/ || echo "No HTML files generated"
    displayName: 'Move Snyk Reports to Results Directory'

  # Step 4: Publish Snyk results as artifacts (for review, but not failing the build)
  - publish: $(Build.ArtifactStagingDirectory)/results
    artifact: snyk-results
    displayName: 'Publish Snyk Results'

  # Step 5: (Optional) List files in temp directory for debugging purposes
  - script: |
      echo "Listing files in temp directory"
      ls -alh /home/vsts/work/_temp/
    displayName: 'List Files in Temp Directory'
