trigger:
  branches:
    include:
      - main  # specify the branch to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'  # use an Ubuntu image for the pipeline

jobs:
  - job: SnykScan
    displayName: 'Snyk Vulnerability Scan'
    steps:
      - task: UsePythonVersion@0  # Use a Python version to install Snyk
        inputs:
          versionSpec: '3.x'
          addToPath: true

      - script: |
          python -m pip install --upgrade pip
          pip install snyk
        displayName: 'Install Snyk CLI'

      - script: |
          snyk auth $(SNYK_TOKEN)  # Make sure you have set your Snyk API token in pipeline secrets
          snyk test  # Run the Snyk vulnerability scan
        displayName: 'Run Snyk Test'
        env:
          SNYK_TOKEN: $(SNYK_TOKEN)  # Ensure you add the Snyk token as a secret in your pipeline
