trigger:
- main  # Adjust as needed for your branch

pool:
  vmImage: ubuntu-latest  # Use an appropriate agent pool (change if required)

steps:
  # Run Snyk Security Scan on Code with Authentication via Service Connection
  - task: SnykSecurityScan@1
    inputs:
      serviceConnectionEndpoint: 'SNYKS'  # Use your correct service connection name
      testType: 'code'  # Scan the source code for vulnerabilities
      failOnIssues: false  # Do NOT fail the build regardless of issues found
      projectName: 'your-project-name'  # Set your project name (auto-filled in the UI)
      organizationName: 'your-org-name'  # Set your Snyk organization name (auto-filled in the UI)
    displayName: 'Run Snyk Code Security Scan'

  # Publish Snyk results as artifacts (for review, but not failing the build)
  - publish: $(System.DefaultWorkingDirectory)/results
    artifact: snyk-results
    displayName: 'Publish Snyk Results'
