trigger:
  branches:
    include:
      - main  # Trigger this pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'  # Use the Ubuntu image for the build agent (you can change the image if needed)

jobs:
  - job: SnykScan
    displayName: 'Run Snyk Security Scan'
    steps:

      # Step 1: Checkout the repository
      - task: Checkout@1  # Checkout the code from the repository (using version 1)
        displayName: 'Checkout Code'
        inputs: {}

      # Step 2: Install Snyk CLI
      - script: |
          npm install -g snyk
        displayName: 'Install Snyk CLI'

      # Step 3: Authenticate with Snyk using the secret variable
      - script: |
          echo $(SNYK) | snyk auth
        displayName: 'Authenticate with Snyk'
        env:
          SNYK_TOKEN: $(SNYK)  # Explicitly mapping the secret variable to an environment variable

      # Step 4: Run the Snyk test and save results in .svc file
      - script: |
          snyk test --all-projects --json > snyk-report.svc
        displayName: 'Run Snyk Test and Generate Results in SVC Format'

      # Step 5: List the contents of the source directory to ensure file existence
      - script: |
          echo "Listing contents of the directory:"
          ls -R $(Build.SourcesDirectory)
        displayName: 'List Directory Contents'

      # Step 6: Publish the results as build artifacts (SVC report)
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.SourcesDirectory)/snyk-report.svc'  # Path to the generated SVC report
          ArtifactName: 'snyk-reports'  # Artifact name
          publishLocation: 'Container'  # Publish to a container for download
