trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
  - job: SnykScan
    displayName: 'Run Snyk Security Scan'
    steps:
      - script: |
          npm install -g snyk
        displayName: 'Install Snyk CLI'
      
      - script: |
          echo $(SNYK) | snyk auth
        displayName: 'Authenticate with Snyk'
        env:
          SNYK_TOKEN: $(SNYK)  # Pass the secret token as an environment variable
      
      - script: |
          snyk test --all-projects
        displayName: 'Run Snyk Test'
